# Generated by Django 4.2.5 on 2023-09-24 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookwriter', '0002_collaboration_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Author', 'Author'), ('Collaborator', 'Collaborator')], default='-', max_length=20),
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('parent_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='bookwriter.section')),
            ],
        ),
    ]
