# Generated by Django 4.2.5 on 2023-09-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwriter', '0003_alter_userprofile_role_subsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('author', 'Author'), ('collaborator', 'Collaborator')], default='-', max_length=20),
        ),
    ]
